### ISSUE TITLE
Замечания к лабораторной №3

### ISSUE THREAD

**Issue by fairay** [LilShkrek/Practice#1]
- [x] Зануление - правильно, arr_t нужно передать по ссылке, чтобы занулилась не локальная переменная
https://github.com/LilShkrek/Practice/blob/5bb6ef27d17bfca1813121028d2b79132e298576/Hometask3/Hometask3/Source.cpp#L19

- [x] Функция не возвращает кода ошибки и не завершается в случае неудачного malloc
https://github.com/LilShkrek/Practice/blob/5bb6ef27d17bfca1813121028d2b79132e298576/Hometask3/Hometask3/Source.cpp#L26

- [x] Делать cleanmem для NULL не нужно
https://github.com/LilShkrek/Practice/blob/5bb6ef27d17bfca1813121028d2b79132e298576/Hometask3/Hometask3/Source.cpp#L32

- [x] Нет очищения памяти в случае неудачи, нет сообщения об ошибке, нет обработки ситуации с нулевым size (realloc работает как free и вернёт NULL)
https://github.com/LilShkrek/Practice/blob/5bb6ef27d17bfca1813121028d2b79132e298576/Hometask3/Hometask3/Source.cpp#L41

**Comment by LilShkrek** [comment]
Исправил. Только вывожу не код ошибки, а просто сообщение о том, что сломалось. Так можно?

**Comment by fairay** [comment]
Осталось только тут поменять и всё готово
https://github.com/LilShkrek/Practice/blob/e288699455c42ee16a91404976f00824fb6a0dec/Hometask3/Hometask3/Source.cpp#L40

**Comment by LilShkrek** [comment]
Вот так ведь?
`void reallocation(arr_t& arr, int size) {   //Подаю изменённый size

	arr_t temp = (int*)realloc(arr, size * sizeof(int));
	if (temp == NULL && size != 0) {

		cout << "ERROR. Realloc failed" << endl;
		cleanmem(arr);
		exit(0);

	}
	else arr = temp;

}`

**Comment by fairay** [comment]
Да, всё правильно
Лаба сдана)
