### ISSUE TITLE
Замечания к лабораторной работе №4

### ISSUE THREAD

**Issue by fairay** [LilShkrek/Practice#2]
В целом замечания связаны с обработкой неудачных realloc-ов. Нужно либо сразу завершать программу (с очисткой всей памяти), либо продолжать (данные исходного стека **должны быть сохранены**, для этого лучше всего работать не с оригинальным стеком, а с его копией).

Так как тут память чистится уже внутри reallocation, проще всего будет завершать программу.

Но если ошибка не связана с памятью, то данные в любом случае должны быть сохранены.

- [x] В случае неудачного push/pop память вспомогательного стека не чистится, а следовательно утекает.
https://github.com/LilShkrek/Practice/blob/890f0d33a58c3dc38392af4083ca328a151f53e1/Hometask4/Hometask4/Source.cpp#L222
https://github.com/LilShkrek/Practice/blob/890f0d33a58c3dc38392af4083ca328a151f53e1/Hometask4/Hometask4/Source.cpp#L258
https://github.com/LilShkrek/Practice/blob/890f0d33a58c3dc38392af4083ca328a151f53e1/Hometask4/Hometask4/Source.cpp#L290
https://github.com/LilShkrek/Practice/blob/890f0d33a58c3dc38392af4083ca328a151f53e1/Hometask4/Hometask4/Source.cpp#L329

- [x] В заданиях 4-6 нет разделения на тип ошибки. В случае, если ошибка связана с размером стека нужно выдавать одно сообщение, если с памятью, то другое
https://github.com/LilShkrek/Practice/blob/890f0d33a58c3dc38392af4083ca328a151f53e1/Hometask4/Hometask4/Source.cpp#L416
https://github.com/LilShkrek/Practice/blob/890f0d33a58c3dc38392af4083ca328a151f53e1/Hometask4/Hometask4/Source.cpp#L422
https://github.com/LilShkrek/Practice/blob/890f0d33a58c3dc38392af4083ca328a151f53e1/Hometask4/Hometask4/Source.cpp#L429

- [x] В случае неудачного push стек будет очищен
https://github.com/LilShkrek/Practice/blob/890f0d33a58c3dc38392af4083ca328a151f53e1/Hometask4/Hometask4/Source.cpp#L371

- [x]  Изменение размера перенести в reallocation
https://github.com/LilShkrek/Practice/blob/890f0d33a58c3dc38392af4083ca328a151f53e1/Hometask4/Hometask4/Source.cpp#L91

**Comment by LilShkrek** [comment]
Вроде исправил

**Comment by LilShkrek** [comment]
Вроде исправил

**Comment by fairay** [comment]
Лаба принята
